#!/usr/bin/env bash
# Idempotent setup for the agent-browser skill.
#
# Run automatically by the SessionStart hook in .claude/settings.json, and safe
# to run by hand at any time. It:
#   1. installs the `agent-browser` CLI globally if it is missing
#   2. puts a `google-chrome` shim on PATH so the CLI finds a browser without
#      downloading one (reuses the pre-installed Chromium when there is one)
#   3. teaches Chrome to trust this sandbox's TLS-inspection CAs
#
# Everything it does is a no-op when already in place, so repeated runs are cheap.

set -uo pipefail

log() { printf 'agent-browser setup: %s\n' "$*" >&2; }

# ---------------------------------------------------------------- 1. the CLI
if ! command -v agent-browser >/dev/null 2>&1; then
  log "installing agent-browser CLI"
  npm install -g agent-browser >/dev/null 2>&1 || log "npm install -g agent-browser failed"
fi

# ------------------------------------------------------------- 2. the browser
find_chrome() {
  local c
  for c in "${PLAYWRIGHT_BROWSERS_PATH:-/opt/pw-browsers}"/chromium-*/chrome-linux/chrome \
           "${PLAYWRIGHT_BROWSERS_PATH:-/opt/pw-browsers}"/chromium/chrome-linux/chrome \
           "$HOME"/.cache/ms-playwright/chromium-*/chrome-linux/chrome \
           /usr/bin/chromium /usr/bin/chromium-browser \
           /usr/bin/google-chrome /usr/bin/google-chrome-stable \
           /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome; do
    [ -x "$c" ] && { printf '%s\n' "$c"; return 0; }
  done
  return 1
}

SHIM=/usr/local/bin/google-chrome
[ -w /usr/local/bin ] || SHIM="$HOME/.local/bin/google-chrome"

# Don't shadow a real browser that is already on PATH and is not our own shim.
existing=$(command -v google-chrome 2>/dev/null || true)
if [ -n "$existing" ] && [ "$existing" != "$SHIM" ]; then
  log "google-chrome already on PATH at $existing; leaving it alone"
elif chrome=$(find_chrome); then
  mkdir -p "$(dirname "$SHIM")"
  cat > "$SHIM" <<EOF
#!/bin/sh
# Generated by .claude/hooks/setup-agent-browser.sh — safe to delete and regenerate.
#
# --no-sandbox            : Chrome refuses to run as root without it.
# --ssl-version-max=tls1.2: the sandbox egress proxy resets Chrome's TLS 1.3
#                           ClientHello. Certificates are still verified.
CHROME_BIN="$chrome"
[ "\$(id -u)" = "0" ] && set -- --no-sandbox --disable-dev-shm-usage "\$@"
[ -n "\${CCR_AGENT_PROXY_ENABLED:-}" ] && set -- --ssl-version-max=tls1.2 "\$@"
exec "\$CHROME_BIN" "\$@"
EOF
  chmod +x "$SHIM"
  log "browser shim -> $chrome"
else
  log "no Chrome/Chromium found; run 'agent-browser install' to download one"
fi

# ------------------------------------------------------------------- 3. CA trust
# Chrome on Linux uses its own root store and ignores /etc/ssl/certs, so the
# sandbox's TLS-inspection CAs have to be handed to it as trust anchors via the
# CACertificates enterprise policy.
CA_DIR=/usr/local/share/ca-certificates
if [ -d "$CA_DIR" ] && ls "$CA_DIR"/*.crt >/dev/null 2>&1; then
  for policy_dir in /etc/chromium/policies/managed /etc/opt/chrome/policies/managed; do
    mkdir -p "$policy_dir" 2>/dev/null || continue
    python3 - "$policy_dir/sandbox-ca.json" "$CA_DIR" <<'PY' 2>/dev/null || log "could not write Chrome CA policy"
import glob, json, os, re, sys

out, ca_dir = sys.argv[1], sys.argv[2]
certs = []
for path in sorted(glob.glob(os.path.join(ca_dir, "*.crt"))):
    with open(path) as fh:
        body = fh.read()
    for der in re.findall(
        r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", body, re.S
    ):
        certs.append("".join(der.split()))
if certs:
    with open(out, "w") as fh:
        json.dump({"CACertificates": certs}, fh, indent=2)
PY
  done
fi

exit 0
